### ISSUE TITLE
Make the border area unclickable 

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#371]
Un-hyperlink the space around the logo: 

![CleanShot 2022-05-05 at 17 02 58](https://user-images.githubusercontent.com/46772424/166915184-1aee16f4-a9ef-4e00-9493-d5f90e16019e.gif)

**Comment by harshit-30** [comment]
@jahnaviraj can you fix this? requires a very small fix

**Comment by jahnaviraj** [comment]
Sure 
Will update by tomorrow eve

**Comment by kamaljohnson** [comment]
Resolved in #802 
thanks @jahnaviraj
