### ISSUE TITLE
Subject icon based on ticket creation via email or portal

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#401]
This icon should represent where the ticket has been created from. there are three places it can be created from: email, customer portal and phone _(when created by an agent)._

![CleanShot 2022-05-13 at 14 20 59@2x](https://user-images.githubusercontent.com/46772424/168247715-fa6bad15-9a08-4b65-a6f1-2731b996a3c7.png)

Icons required: 
1. Email: 
2. Phone: 
3. Customer Portal:

**Comment by kamaljohnson** [comment]
Duplicate issues
