### ISSUE TITLE
feat: Customer Management

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#461]
The ability to manage an organization is absent from the current design. below are the expected flows to be implemented:

1. Organization list:
- actions: add a new organization, add filter
- select multiple organizations
- bulk action should only consist of the Delete option
- Columns: Name, number of contacts linked to it

2. Organization form:
- shows name (editable), contacts linked to it (add 'link users' as an option)
- shows all their tickets
- an option to create a new ticket from the same
- option to delete

Organization fields: 
- Name 
- Domains (`placeholder - acmeltd.com, mycompany.com`, `tooltip - Contacts and tickets with similar domains will be added to this organization.`)

these are features that are supposed to be implemented @kamaljohnson.
@nish7x we will need screens for all these features.

**Comment by harshit-30** [comment]
@nish7x we'll execute this from the next sprint, let's discuss the editing of forms on call and get done with this design before this Friday?

**Comment by kishor-desarda** [comment]
Hi,

Can you also auto populate Customers/Vendors from ERPNext as a part of organization ?

**Comment by fadilsid** [comment]
resolved in #840
