### ISSUE TITLE
feat: keyboard shortcuts

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#470]
Ticket View keyboard shortcuts:

- to mark tickets directly as Replied: Cmd + Option + R
- to mark tickets directly as Resolved: Cmd + Option + E
- to mark tickets directly as Closed: Cmd + Option + C

**Comment by kamaljohnson** [comment]
> Suggesting some more
> 
> * Copy ticket id (useful to refer to in other contexts)
> 
> Will add more here as I think of more

created a new issue for this
