### ISSUE TITLE
new text editor - issues 

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#581]
- [x] #597
- [x] The alignment button doesn't work
- [x] No way to add images from the finder
- [x] The T _(the one which removes formatting)_ icon doesn't work too. 
- [x] Add Cmd+Enter as a shortcut to send

**Comment by kamaljohnson** [comment]
Fixed - **Add Cmd+Enter as a shortcut to send** in #559

**Comment by harshit-30** [comment]
> Fixed - **Add Cmd+Enter as a shortcut to send** in #559

Does it work with `windows` users? they have `ctrl+enter`.

**Comment by kamaljohnson** [comment]
> * [ ]  No way to add images from the finder
> *

yes

**Comment by kamaljohnson** [comment]
>  The T (the one which removes formatting) icon doesn't work too.

leaving this one for now, removed this tool from all the text editor instances
