### ISSUE TITLE
Errors - Holiday List Default not found  & The resource you are looking for is not available

### ISSUE THREAD

**Issue by fkalpana** [frappe/desk#587]
Two error pops up while creating new ticket, even though Default holiday list is already set.
Looks like a bug

<img width="685" alt="Screen Shot 2022-07-23 at 1 15 55 PM" src="https://user-images.githubusercontent.com/69480716/180601000-e099d6c8-51f6-4b1f-b7e9-0f3afc3280d5.png">

**Comment by kamaljohnson** [comment]
@fkalpana could you please share the console log too, while this is happening. This could help up debug the issue

**Comment by fkalpana** [comment]
Thanks Johnson,

Please see the chrome console log here. If you need to collect any other
log, please send me how-to-do . Our instance is in production mode.

jquery.js:10109          POST
https://zulal.erpgulf.net:5583/api/method/frappe.client.save 404 (NOT FOUND)
send @ jquery.js:10109
ajax @ jquery.js:9690
frappe.request.call @ request.js:253
frappe.call @ request.js:103
(anonymous) @ quick_entry.js:161
insert @ quick_entry.js:159
(anonymous) @ quick_entry.js:150
(anonymous) @ dialog.js:155
dispatch @ jquery.js:5430
u1.handle @ jquery.js:5234


Farook

**Comment by kamaljohnson** [comment]
@fkalpana, does your site have ERPNext installed ??
We haven't tested the compatibility of Frappe Desk with ERPNext yet, I think even if this issue is resolved there might be other issues.

**Comment by kamaljohnson** [comment]
This should be fixed in #589
