### ISSUE TITLE
comments are not displayed without refreshing 

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#593]
After commenting, the page requires a refresh for the agent to reflect it. 
![CleanShot 2022-07-27 at 19 14 47](https://user-images.githubusercontent.com/46772424/181265467-a2cbaaaa-ba9d-4365-9d0a-93f5d660484b.gif)

**Comment by harshit-30** [comment]
@kamaljohnson is this fixed?

**Comment by kamaljohnson** [comment]
This issue is not there anymore
