### ISSUE TITLE
Design changelog page for website

### ISSUE THREAD

**Issue by nish7x** [frappe/desk#605]

**Comment by nish7x** [comment]
@harshit-30 

Option 1 

![changelog 4](https://user-images.githubusercontent.com/8917840/186136849-2cf28a46-4688-41b7-897d-a7e703aa14b1.png)

---

Option 2

![changelog 3](https://user-images.githubusercontent.com/8917840/186136944-18c039ac-dc58-46f3-8b19-c4a9fbd12dac.png)

---

Option 3 

![changelog 2](https://user-images.githubusercontent.com/8917840/186136994-f3f0496d-a1a6-4de1-8f1b-1e8f743c35a6.png)

---

Option 4 

![changelog](https://user-images.githubusercontent.com/8917840/186137036-fee47b3c-f650-41c7-97d5-af8c4ccc5515.png)

**Comment by netchampfaris** [comment]
I like Option 1 and 2 better. But there needs to be anchoring with the hero section.

Examples:
https://www.lemonsqueezy.com/changelog/
https://www.chatwoot.com/changelog/
