### ISSUE TITLE
Country Issue while Signup for Trial

### ISSUE THREAD

**Issue by sumeetagra** [frappe/desk#621]
Cannot select any country during signup for trial.

**Comment by harshit-30** [comment]
@kamaljohnson the combo box takes about 15-20 secs to reflect the list of available names: 
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/46772424/185057860-a8bdd55d-901d-4aa5-926e-f8e506de3ca8.png">


@sumeetagra You can type it manually, it will work.

**Comment by kamaljohnson** [comment]
@sumeetagra this issue is now fixed in frappedesk signup page.
