### ISSUE TITLE
[enhancement] editor config required

### ISSUE THREAD

**Issue by jahnaviraj** [frappe/desk#639]
If you could provide editor.conf file, it would be easier to track changes more effectively. Because of different editor configs, changes come in indentations, comma's, semi colon's. Makes it difficult to review the custom changes made when working on the file.

**Comment by harshit-30** [comment]
@kamaljohnson please review this after the sprint.

**Comment by harshit-30** [comment]
@kamaljohnson following up on this. 

Cc. @jahnaviraj
