### ISSUE TITLE
Ticket View - Timeline should be in descending chronological order 

### ISSUE THREAD

**Issue by nish7x** [frappe/desk#644]
![telegram-cloud-photo-size-2-5197554609286134628-y](https://user-images.githubusercontent.com/8917840/185924006-25f9ba25-a93e-46bb-b5ed-14b17bd587e7.jpg)

**Comment by harshit-30** [comment]
@kamaljohnson i assume this was finished.

**Comment by kamaljohnson** [comment]
yes
