### ISSUE TITLE
[Bug] Pagination on Tickets not Working with Update Frappe-ui Version

### ISSUE THREAD

**Issue by jahnaviraj** [frappe/desk#716]
Going on _/frappedesk/tickets/<ticket_id>/?page=2_  throws " can not concat to null " error.
Clicking on Page 2 from bottom page number buttons does not update the list. 

From Debugging I found the issue is with Frappe-ui updated version, not sure which version exact. 
But version 0.0.38 works for pagination. 

The error is coming from resources.js file  -> get_list function from frappe-ui .

**Comment by jahnaviraj** [comment]
any updates? 
@kamaljohnson @harshit-30

**Comment by kamaljohnson** [comment]
> any updates? @kamaljohnson @harshit-30

@jahnaviraj I have made a temporary fix for this in #741, will release a new pagination component shortly
