### ISSUE TITLE
Ticket list in customer portal not available

### ISSUE THREAD

**Issue by hadeeld7** [frappe/desk#717]
Hi, i am facing an issue with enabling list view in ticket webform that when the user is accessing for example this link https://sitedomail/support/tickets, he will not be able to view a list of his tickets. only he will be able to view his submitted ticket accessing from a link sent to him by email updates.

refer to this screenshot from customer portal :
<img width="1340" alt="Screen Shot 2022-09-13 at 12 32 41 PM" src="https://user-images.githubusercontent.com/45418118/189866917-54217217-2472-4d2d-8816-89d937f43700.png">

Thank you

**Comment by harshit-30** [comment]
@kamaljohnson please check on this.
