### ISSUE TITLE
Rename the 'Powered by...' in KB footer

### ISSUE THREAD

**Issue by nish7x** [frappe/desk#736]
Currently says Frappe Helpdesk. 

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8917840/192958559-1b327cb1-27a1-43c1-89a3-66d430d75cce.png">

(https://frappedesk.frappe.cloud/support/kb/getting-started/convert-your-support-emails-to-tickets-in-frappe-desk)

**Comment by kamaljohnson** [comment]
The UI has been changed
