### ISSUE TITLE
Knowledge Base Article See on website error

### ISSUE THREAD

**Issue by jpettan** [frappe/desk#746]
![F5455467-A827-4439-BE7B-4CD55DFE84EB](https://user-images.githubusercontent.com/115516364/194985646-8259e274-c06b-4421-895b-b07fb8068719.png)

The following error is shown when you hit the ‘see on website’ option for kb article. Platform - frappe cloud.
ERPNext 14.
Version - uptodate

**Comment by jpettan** [comment]
> @jpettan could you please specify the exact commit of frappedesk, in which you are on

3afa5c7

**Comment by kamaljohnson** [comment]
Got it,
this is happening due to a code formatting issue here #742
it added a newline to "Frappe Desk Settings" text in one of the .html pages 

fixing it now,

thanks for pointing this out
