### ISSUE TITLE
ModuleNotFoundError: No module named 'frappe.core.doctype.frappe\n\t\t\t\t\tdesk_settings'

### ISSUE THREAD

**Issue by fadilsiddique** [frappe/desk#747]
Getting module not found error after instaling frappedesk in site. I'm able access the desk but not website pages. redirecting to website pages gives this error.

![Screenshot from 2022-10-11 18-13-34](https://user-images.githubusercontent.com/48912196/195094591-48b59140-8c43-49d2-abc9-4088b0088c94.png)

**Comment by kamaljohnson** [comment]
@fadilsiddique, could you please specify the exact web page you where trying to open

**Comment by kamaljohnson** [comment]
This is happening due to a code formatting issue here https://github.com/frappe/desk/pull/742
it added a newline to "Frappe Desk Settings" text in one of the .html pages

fixing it now,

thanks for pointing this out
