### ISSUE TITLE
Setting ticket type hangs

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/desk#762]
Steps to reproduce:

1. Add a new reply to the ticket
2. Try setting the type

Spins forever:

![CleanShot 2022-11-01 at 18 28 21@2x](https://user-images.githubusercontent.com/34810212/199237684-b2fc03c2-6365-42d4-93b3-7521749ca949.png)

This **might** be the cause:

<img width="1440" alt="CleanShot 2022-11-01 at 18 29 12@2x" src="https://user-images.githubusercontent.com/34810212/199237896-7ff9b8a2-4ad5-451d-8dda-09d567064a03.png">

**Comment by Ravn10** [comment]
Any update on this issue team

**Comment by harshit-30** [comment]
@kamaljohnson ??

**Comment by kamaljohnson** [comment]
This issue should be fixed with #868 and #832
