### ISSUE TITLE
Could not access the list of tickets, however the count was displayed. 

### ISSUE THREAD

**Issue by aiswaryals1997** [frappe/desk#765]
Coudn’t view the ticket list, but showing the count.

**Comment by kamaljohnson** [comment]
@aiswaryals1997, Could you please share the console log, which can be accessed by `fn + F12`.

**Comment by aiswaryals1997** [comment]
![Screenshot from 2022-11-03 14-13-26](https://user-images.githubusercontent.com/61047968/199678545-9cff4b0a-8342-4c91-81a7-90c66275692a.png)

**Comment by kamaljohnson** [comment]
@aiswaryals1997, I meant the webpage console log, sorry to be confusing.

https://user-images.githubusercontent.com/22856401/199680212-85360824-9adb-4037-89e7-84b8babf45ca.mov

**Comment by aiswaryals1997** [comment]
![Screenshot from 2022-11-03 14-26-46](https://user-images.githubusercontent.com/61047968/199680927-06d3c82b-7869-4bfc-85d9-17aecca64bc7.png)

This is our webpage console log.

Sorry for the mistake!!!

**Comment by aiswaryals1997** [comment]
![Screenshot from 2022-11-03 14-29-48](https://user-images.githubusercontent.com/61047968/199681482-ac732c59-e4cf-4019-99f2-348f2414d58f.png)

This is our webpage console log.

Sorry for the mistake!!!

**Comment by aiswaryals1997** [comment]
![Screenshot from 2022-11-03 14-39-58](https://user-images.githubusercontent.com/61047968/199683328-d843f9c5-8b18-4763-8aab-bcb9aa696d75.png)

This is the console of our webpage.

Sorry for the mistake!!!

**Comment by kamaljohnson** [comment]
@aiswaryals1997, It seems like there was an error while accessing an API, could you share the Click on the Network tab and show the Response of that API. also please refresh the page after opening the Network tab (it does not show past API calls)

Also If you are using an older version of Frappe or Frappe Desk could you please update it before that.

**Comment by aiswaryals1997** [comment]
![Screenshot from 2022-11-03 15-39-24](https://user-images.githubusercontent.com/61047968/199694578-92fce734-0b16-48c0-aad1-6c702c8372cd.png)
Frappe Version is V13 
Can we update Frappe without losing the existing things that we have done till now?

**Comment by aiswaryals1997** [comment]
Issue Resolved!!!

Thank you!!!

**Comment by kamaljohnson** [comment]
Closing the issue since its resolved

**Comment by kamaljohnson** [comment]
> ![Screenshot from 2022-11-03 15-39-24](https://user-images.githubusercontent.com/61047968/199694578-92fce734-0b16-48c0-aad1-6c702c8372cd.png) Frappe Version is V13 Can we update Frappe without losing the existing things that we have done till now?

@aiswaryals1997 updating frappe will not affect the frappedesk instance.
