### ISSUE TITLE
All Tickets view only shows 20 tickets

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/desk#767]
To Reproduce: Create 21 or more tickets. Navigate to All Tickets in frappedesk. The total ticket count displayed in the upper right is correct but only 20 tickets are displayed in the list. 

Also, frappedesk should probably display a version somewhere inside the UI to facilitate reporting issues for frappecloud-based deployments.

**Comment by jahnaviraj** [comment]
Are the pagination buttons visible to you? You can access more tickets on further pages.

**Comment by harshit-30** [comment]
@joshuarestivo we're working on PR #779 - this should fix the pagination issue as well, if it doesn't - we will fix it after this PR is merged.
