### ISSUE TITLE
In which file we can edit the knowledge base page?

### ISSUE THREAD

**Issue by aiswaryals1997** [frappe/desk#780]
In which file we can edit the knowledge base page?

**Comment by esafwan** [comment]
In the frappedesk application, Knowledge Base code can been seem in the following place:

**Vue App:**
1. `bench14/apps/frappedesk/desk/src/pages/desk/kb`
2. `bench14/apps/frappedesk/desk/src/components/desk/kb`
3. `bench14/apps/frappedesk/desk/src/components/portal/kb`
4. `bench14/apps/frappedesk/desk/src/components/global/kb`

**Frappe:**
1. Doctype can be found: `bench14/apps/frappedesk/frappedesk/frappedesk/doctype`
