### ISSUE TITLE
Reply mails don't cover subject of ticket

### ISSUE THREAD

**Issue by moroslantia** [frappe/desk#846]
### Reproduce
Reply to an ticket

### Expected
Mail sent to ticket issuer with Ticket numeber and title in the subject line to follow up

### Observed
Mail sent with subject of "[Ticket #####] New reply" 
The static text "New reply" is not clear enough for the issuer to understand easily what the mail is about

**Comment by harshit-30** [comment]
@kamaljohnson can we fix this on priority?

**Comment by harshit-30** [comment]
@kamaljohnson ???
