### ISSUE TITLE
contacts are not fetched

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#872]
Despite having contacts in the backend, the list reflects none: 
![Screenshot 2022-12-16 at 04 20 06](https://user-images.githubusercontent.com/46772424/207983726-bc7ccc6e-11a4-4462-ae9e-fdbdc8d09a36.gif)

In the Contact List, there are five contacts: 
![Screenshot 2022-12-16 at 04 19 08](https://user-images.githubusercontent.com/46772424/207983579-209d9f19-0273-4116-8429-e29838d7e5ff.png)

**Comment by kamaljohnson** [comment]
The contact info editing is removed for now, this issues: #923 will be tracked here on
