### ISSUE TITLE
sidebar icon color mismatch

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#875]
The ticket icon is darker compared to the other ones:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/46772424/207989676-715bb4ba-0655-43e5-a43b-37faf646c830.png">

**Comment by fadilsid** [comment]
resolved in #912 

![Image](https://user-images.githubusercontent.com/73826691/210072645-498d5fd4-6134-4d72-9c42-a92777b26759.png)
