### ISSUE TITLE
extend customer feature in contacts

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#906]
- [x] add Customer column in the Contact list
- [x] add a field in Contact to reflect which Customer they belong to 
- [x] the above field should be editable and should showcase every other customer
- [x] the same should be fetched in the ticket 
- [x] change the design as per the below image
<img width="423" alt="image" src="https://user-images.githubusercontent.com/46772424/210016291-031fe3b9-55d0-42c9-938a-e163e5229133.png">

- [x] change the edit icon as seen in Figma with the same size as before
- [ ] remove semibold from the breadcrumb and make it normal

**Comment by fadilsid** [comment]
@harshit-30 regarding breadcruumb, you are referring to ticket info page breadcrumb right?
