### ISSUE TITLE
I cannot create tickets from the portal

### ISSUE THREAD

**Issue by federicocalvo** [frappe/desk#919]
I can't upload tickets from the portal, neither from an administrator user, nor from an email that is as a contact.

Errors in console:
![Captura de pantalla 2023-01-05 a la(s) 13 11 09](https://user-images.githubusercontent.com/7256766/210850302-2e879806-8131-496d-bf27-08f4fe5647dd.png)

Fdesk Version: 0.5.13 updated todoy from main branch

**Comment by kamaljohnson** [comment]
This issue is fixed in #920
